# Generated by Django 3.1.8 on 2021-04-26 19:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateTimeField(editable=False)),
                ('updated', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='BotConfigurationVariables',
            fields=[
                ('timestamped_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.timestamped')),
                ('name', models.CharField(max_length=50)),
                ('bot_on', models.BooleanField(default=False)),
                ('pair', models.CharField(max_length=50)),
                ('buy', models.FloatField()),
                ('upswing_buy', models.FloatField()),
                ('sell', models.FloatField()),
                ('downswing_sell', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Bot Configuration Variables',
            },
            bases=('bot.timestamped',),
        ),
    ]
