# Generated by Django 3.1.8 on 2021-04-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('timestamped_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.timestamped')),
                ('completed', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=100)),
                ('pair', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=3)),
                ('order_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('total', models.FloatField()),
            ],
            bases=('bot.timestamped',),
        ),
        migrations.AlterField(
            model_name='botconfigurationvariables',
            name='pair',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum')], max_length=50),
        ),
    ]
