# Generated by Django 3.1.8 on 2021-04-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210426_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfigurationvariables',
            name='auto_cancel_order_after',
            field=models.IntegerField(default=10),
        ),
    ]
