# Generated by Django 3.1.8 on 2021-04-26 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botconfigurationvariables_auto_cancel_order_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfigurationvariables',
            name='pair',
            field=models.CharField(choices=[('BTC/USD', 'Bitcoin/USDollar'), ('ETH/USD', 'Ethereum/USDollar')], max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pair',
            field=models.CharField(choices=[('BTC/USD', 'Bitcoin/USDollar'), ('ETH/USD', 'Ethereum/USDollar')], max_length=7),
        ),
        migrations.AlterField(
            model_name='timestamped',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
