# Generated by Django 3.1.8 on 2021-04-27 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210426_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='completed',
        ),
    ]
