# Generated by Django 3.1.8 on 2021-04-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210427_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botconfigurationvariables',
            name='auto_cancel_order_after',
        ),
    ]
