# Generated by Django 3.1.8 on 2021-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20210427_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfigurationvariables',
            name='fee',
            field=models.FloatField(default=0.0),
        ),
    ]
