# Generated by Django 3.1.8 on 2021-04-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_botconfigurationvariables_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfigurationvariables',
            name='auto_cancel_order_period',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
